# Generated by Django 2.1.2 on 2018-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='score',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='scoreUpdatedAt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.TextField(default='0'),
        ),
    ]
